version: "3.8"
services:
  mysqldb:
    image: mysql:8.0.28
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_NAME
    ports:
      - $MYSQL_EXTERNAL_PORT:$MYSQL_INTERNAL_PORT
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend

  eureka:
    image: osiguranjeraf2022/eureka
    env_file: ./.env
    ports:
      - $EUREKA_EXTERNAL_PORT:$EUREKA_INTERNAL_PORT
    volumes:
      - eureka:/root/.m2
    stdin_open: true
    tty: true
    networks:
      - backend

  usercrud:
    depends_on:
      - mysqldb
      - eureka
    image: osiguranjeraf2022/user-crud
    env_file: ./.env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:$MYSQL_INTERNAL_PORT/$MYSQL_NAME?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: $MYSQL_PASSWORD
    ports:
      - $USERCRUD_EXTERNAL_PORT:$USERCRUD_INTERNAL_PORT
    volumes:
      - usercrud:/root/.m2
    stdin_open: true
    tty: true
    networks:
      - backend

  gateway:
    depends_on:
      - usercrud
    image: osiguranjeraf2022/gateway
    env_file: ./.env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:$MYSQL_INTERNAL_PORT/$MYSQL_NAME?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: $MYSQL_PASSWORD
      ZUUL_ROUTES_USER_URL: http://usercrud:$USERCRUD_INTERNAL_PORT/api/users
      ZUUL_ROUTES_SECURITIES_URL: http://securities:$SECURITIES_INTERNAL_PORT/api
    ports:
      - $GATEWAY_EXTERNAL_PORT:$GATEWAY_INTERNAL_PORT
    networks:
      - nginx
      - backend
    volumes:
      - gateway:/root/.m2
    stdin_open: true
    tty: true


  securities:
    depends_on:
      - mysqldb
      - eureka
    image: osiguranjeraf2022/securities
    env_file: ./.env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:$MYSQL_INTERNAL_PORT/$MYSQL_NAME?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: $MYSQL_PASSWORD
    ports:
      - $SECURITIES_EXTERNAL_PORT:$SECURITIES_INTERNAL_PORT
    volumes:
      - securities:/root/.m2
    stdin_open: true
    tty: true
    networks:
      - backend

  frontend:
    image: osiguranjeraf2022/frontend
    ports:
      - '80:80'
    networks:
      - nginx

  flask:
    container_name: python-flask
    image: osiguranjeraf2022/python-service
    build:
      context: python-service
      dockerfile: Dockerfile
    ports:
      - "9999:5000"
    volumes:
      - ./python-service:/app
    networks:
      - backend

volumes:
  db:
  eureka:
  gateway:
  usercrud:
  securities:
  flask:

networks:
  nginx:
    driver: bridge
  backend:
    driver: bridge