version: "3.8"
services:
  mysqldb:
    build: mysql
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_NAME
    ports:
      - $MYSQL_EXTERNAL_PORT:$MYSQL_INTERNAL_PORT
    volumes:
      - db:/var/lib/mysql
  eureka:
    build: ./eureka
    env_file: ./.env
    ports:
      - $EUREKA_EXTERNAL_PORT:$EUREKA_INTERNAL_PORT
    volumes:
      - eureka:/root/.m2
    stdin_open: true
    tty: true

  usercrud:
    depends_on:
      - mysqldb
      - eureka
    build: ./user-crud
    env_file: ./.env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:$MYSQL_INTERNAL_PORT/$MYSQL_NAME?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: $MYSQL_PASSWORD
    ports:
      - $USERCRUD_EXTERNAL_PORT:$USERCRUD_INTERNAL_PORT
    volumes:
      - usercrud:/root/.m2
    stdin_open: true
    tty: true

  gateway:
    depends_on:
      - usercrud
    build: ./gateway-app
    env_file: ./.env
    environment:
      # No idea why but it doesnt work with env as in futures service
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:$MYSQL_INTERNAL_PORT/$MYSQL_NAME?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: $MYSQL_PASSWORD
      ZUUL_ROUTES_USER_URL: http://usercrud:$USERCRUD_INTERNAL_PORT/api/users
      ZUUL_ROUTES_SECURITIES_URL: http://securities:$SECURITIES_INTERNAL_PORT/api
    ports:
      - $GATEWAY_EXTERNAL_PORT:$GATEWAY_INTERNAL_PORT
    volumes:
      - gateway:/root/.m2
    stdin_open: true
    tty: true


  securities:
    depends_on:
      - mysqldb
      - eureka
    build: ./securities
    env_file: ./.env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:$MYSQL_INTERNAL_PORT/$MYSQL_NAME?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: $MYSQL_PASSWORD
    ports:
      - $SECURITIES_EXTERNAL_PORT:$SECURITIES_INTERNAL_PORT
    volumes:
      - securities:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
  eureka:
  gateway:
  usercrud:
  securities: