version: '3.6'
services:
  flask:
    container_name: python-flask
    image: python-service
    build:
      context: python-service
      dockerfile: Dockerfile
    ports:
      - "9999:5000"
    volumes:
      - ./python-service:/app